function highlight(t){const words=t.split(' ');if(words.length<4)return t;const cut=Math.ceil(words.length*.58);return `${words.slice(0,cut).join(' ')} <span class="cyan">${words.slice(cut).join(' ')}</span>`}
function renderAll(){
 const pack=content[state.lang];document.documentElement.lang=state.lang;els.stage.innerHTML=pack.scenes.map(renderScene).join('');els.title.textContent=pack.title;els.langVisible.textContent=languageLabels[state.lang]||'English';els.languageButton.setAttribute('aria-label',`${languageAriaLabels[state.lang]}: ${languageLabels[state.lang]||'English'}`);els.languageMenu.setAttribute('aria-label',languageAriaLabels[state.lang]);syncLanguageMenu();els.rate.value=state.rate;els.captions.classList.toggle('on',state.captions);els.captions.setAttribute('aria-pressed',state.captions);
 $$('[data-ui]').forEach(el=>{const k=el.dataset.ui;if(ui[state.lang][k])el.textContent=ui[state.lang][k]});
 els.languageMenu.querySelector('.language-menu-note').textContent=state.lang==='en'?'↑ ↓ to move · Enter to select · Esc to close':state.lang==='ja'?'↑ ↓ で移動 · Enter で選択 · Esc で閉じる':state.lang==='zh-TW'?'↑ ↓ 移動 · Enter 選擇 · Esc 關閉':'↑ ↓ 移动 · Enter 选择 · Esc 关闭';els.searchInput.placeholder=ui[state.lang].placeholder;els.search.setAttribute('aria-label',ui[state.lang].search);els.search.title=ui[state.lang].search;els.narr.setAttribute('aria-label',ui[state.lang].narration);els.narr.title=ui[state.lang].narration;els.audio.setAttribute('aria-label',ui[state.lang].audioSettings);els.audio.title=ui[state.lang].audioSettings;
 bindDynamic();renderMenu();populateVoices();showScene(Math.min(state.index,pack.scenes.length-1),false);runSearch('');
}
function bindDynamic(){
 $$('[data-jump]').forEach(b=>b.addEventListener('click',()=>showScene(Number(b.dataset.jump))));
 $$('[data-reveal]').forEach(b=>b.addEventListener('click',()=>b.classList.toggle('revealed')));
 $$('[data-answer]').forEach(b=>b.addEventListener('click',()=>answerQuestion(Number(b.dataset.answer))));
}
function renderMenu(){const scenes=content[state.lang].scenes;const groups={};scenes.forEach((s,i)=>(groups[s.module]??=[]).push({s,i}));els.menuList.innerHTML=Object.entries(groups).map(([m,arr])=>`<section class="module-block"><h3 class="module-title">${m}</h3>${arr.map(({s,i})=>`<button class="menu-item ${i===state.index?'active':''}" data-menu-index="${i}"><span class="item-title">${s.title}</span><span class="item-subtitle">${s.subtitle}</span></button>`).join('')}</section>`).join('');$$('[data-menu-index]').forEach(b=>b.onclick=()=>{showScene(Number(b.dataset.menuIndex));closeOverlays()})}
function showScene(index,saveState=true){
 const scenes=content[state.lang].scenes;if(index<0||index>=scenes.length)return;cancelSpeech();state.index=index;if(saveState)save();$$('.scene').forEach((s,i)=>s.classList.toggle('active',i===index));const scene=scenes[index];els.subtitle.textContent=scene.subtitle;els.prev.disabled=index===0;els.next.disabled=index===scenes.length-1;const pct=Math.round(((index+1)/scenes.length)*100);els.progress.style.width=pct+'%';els.progressBar.setAttribute('aria-valuenow',pct);els.progressPercent.textContent=pct+'%';els.progressModule.textContent=scene.module;els.counter.textContent=`${ui[state.lang].scene} ${index+1} ${ui[state.lang].of} ${scenes.length}`;renderMenu();restoreAnswer();if(state.auto){if(scene.type==='assessmentIntro'||scene.type==='question'){stopAutoPlay(ui[state.lang].assessmentPaused)}else{setTimeout(()=>playCurrentSceneThenAdvance(),280)}}
}
function goNext(){if(state.index<content[state.lang].scenes.length-1)showScene(state.index+1)}function goPrevious(){if(state.index>0)showScene(state.index-1)}
function answerQuestion(choice){const scene=content[state.lang].scenes[state.index];state.answers[state.lang]=choice;save();const feedback=$('#feedback');$$('[data-answer]').forEach((b,i)=>{b.classList.remove('selected','correct','incorrect');if(i===choice)b.classList.add('selected',choice===scene.correct?'correct':'incorrect');if(choice!==scene.correct&&i===scene.correct)b.classList.add('correct')});feedback.textContent=choice===scene.correct?ui[state.lang].correct:ui[state.lang].incorrect;feedback.classList.add('show')}
function restoreAnswer(){const scene=content[state.lang].scenes[state.index];if(scene.type!=='question')return;const answer=state.answers[state.lang];if(Number.isInteger(answer))answerQuestion(answer)}
