const STORAGE_KEY='micas-interactive-ui-demo-v3.1.10';
const ui=window.MICAS_UI;
const content=window.MICAS_CONTENT;
let state={lang:'en',index:0,auto:false,captions:false,rate:1,selectedVoice:{},answers:{},version:'3.1.10'};
try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved&&saved.version===state.version)state={...state,...saved}}catch(e){}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const languageLabels={en:'English','zh-CN':'简体中文','zh-TW':'繁體中文',ja:'日本語'};
const languageAriaLabels={en:'Course language','zh-CN':'课程语言','zh-TW':'課程語言',ja:'コース言語'};
const els={stage:$('#sceneStage'),title:$('#courseTitle'),subtitle:$('#courseSubtitle'),languagePicker:$('#languagePicker'),languageButton:$('#languageButton'),languageMenu:$('#languageMenu'),languageOptions:$$('.language-option'),langVisible:$('#languageVisible'),auto:$('#autoPlayBtn'),full:$('#fullscreenBtn'),prev:$('#prevBtn'),next:$('#nextBtn'),menu:$('#menuBtn'),search:$('#searchBtn'),narr:$('#narrationBtn'),audio:$('#audioBtn'),counter:$('#sceneCounter'),progress:$('#progressFill'),progressBar:$('.progress-track'),progressModule:$('#progressModule'),progressPercent:$('#progressPercent'),drawer:$('#drawer'),searchPanel:$('#searchPanel'),backdrop:$('#backdrop'),menuList:$('#menuList'),searchInput:$('#searchInput'),searchCount:$('#searchCount'),searchResults:$('#searchResults'),audioPopover:$('#audioPopover'),voiceSelect:$('#voiceSelect'),rate:$('#rateRange'),captions:$('#captionsSwitch'),toast:$('#toast')};
let voices=[],activeUtterances=[],autoPlayRunId=0,toastTimer;
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function icon(name){const map={arrow:'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 18 6-6-6-6"/></svg>',play:'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 7 8 5-8 5z"/></svg>',check:'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 12 4 4L19 6"/></svg>'};return map[name]||''}
function renderScene(scene,i){
 const common=`<div class="module-chip">${scene.module}</div>`;
 if(scene.type==='hero')return `<section class="scene" data-index="${i}"><div class="scene-inner"><div class="hero-grid"><div class="hero-copy"><div class="eyebrow">${scene.eyebrow}</div><h1 class="hero-title">${highlight(scene.title)}</h1><p class="hero-description">${scene.lead}</p><div class="hero-actions"><button class="primary-action" data-jump="1">${ui[state.lang].next} ${icon('arrow')}</button><span class="secondary-action">${ui[state.lang].demoOnly}</span></div></div><div class="visual-card" aria-label="Micas training interface concept"><div class="orbit one"></div><div class="orbit two"></div><div class="orbit three"></div><div class="core-badge"><svg viewBox="0 0 120 120" fill="none"><rect x="22" y="30" width="76" height="60" rx="12" stroke="#76e4ee" stroke-width="4"/><path d="M34 46h52M34 60h52M34 74h34" stroke="#29c5d8" stroke-width="5" stroke-linecap="round"/><circle cx="84" cy="74" r="6" fill="#43d6a0"/></svg></div><span class="float-chip a">${scene.chips[0]}</span><span class="float-chip b">${scene.chips[1]}</span><span class="float-chip c">${scene.chips[2]}</span></div></div></div></section>`;
 if(scene.type==='device')return `<section class="scene" data-index="${i}"><div class="scene-inner"><div class="product-stage"><div class="content-header"><div>${common}<h1 class="scene-title">${scene.title}</h1></div><p class="scene-lead">${scene.lead}</p></div><div class="device-layout"><div class="device-frame"><svg viewBox="0 0 980 360" role="img" aria-label="Conceptual network switch front panel"><defs><linearGradient id="chassis" x1="0" x2="1"><stop stop-color="#243a42"/><stop offset=".5" stop-color="#0b1920"/><stop offset="1" stop-color="#263f48"/></linearGradient><linearGradient id="port" x1="0" x2="1"><stop stop-color="#0a3e4c"/><stop offset="1" stop-color="#086d7f"/></linearGradient></defs><rect x="40" y="82" width="900" height="196" rx="22" fill="url(#chassis)" stroke="#6f8991" stroke-width="4"/><rect x="65" y="112" width="105" height="136" rx="12" fill="#e9f4f6"/><path d="M84 144h68M84 170h68M84 196h52" stroke="#00899f" stroke-width="8" stroke-linecap="round"/><g id="ports">${Array.from({length:16},(_,n)=>{const x=205+(n%8)*82,y=n<8?112:190;return `<rect x="${x}" y="${y}" width="64" height="48" rx="7" fill="url(#port)" stroke="#7de6ef" stroke-width="2"/><circle cx="${x+52}" cy="${y+11}" r="4" fill="${n%3===0?'#43d6a0':'#29c5d8'}"/>`}).join('')}</g><rect x="868" y="112" width="48" height="136" rx="8" fill="#172a31"/><circle cx="892" cy="140" r="9" fill="#43d6a0"/><circle cx="892" cy="174" r="9" fill="#ffbf47"/><circle cx="892" cy="208" r="9" fill="#29c5d8"/></svg><span class="device-caption">Concept illustration • full view</span></div><div class="point-stack">${scene.points.map((p,n)=>`<article class="point-card"><div class="point-number">0${n+1}</div><div><h3>${p[0]}</h3><p>${p[1]}</p></div></article>`).join('')}</div></div></div></div></section>`;
 if(scene.type==='metrics')return `<section class="scene" data-index="${i}"><div class="scene-inner"><div class="metric-stage"><div class="metric-display">${common}<div class="big-number">20<span style="font-size:.42em">px+</span></div><div class="metric-label">${scene.title}</div><p class="scene-lead">${scene.lead}</p></div><div class="metric-grid">${scene.metrics.map(m=>`<article class="metric-card"><div class="value">${m[0]}</div><div class="label">${m[1]}</div></article>`).join('')}</div></div></div></section>`;
 if(scene.type==='process')return `<section class="scene" data-index="${i}"><div class="scene-inner"><div class="process-stage"><div>${common}<h1 class="scene-title">${scene.title}</h1><p class="scene-lead">${scene.lead}</p></div><div class="process-ribbon">${scene.steps.map(s=>`<article class="process-step"><div class="step-index step-number">${s[0]}</div><div><h3>${s[1]}</h3><p>${s[2]}</p></div></article>`).join('')}</div></div></div></section>`;
 if(scene.type==='practice')return `<section class="scene" data-index="${i}"><div class="scene-inner"><div class="practice-stage"><div>${common}<h1 class="scene-title">${scene.title}</h1><p class="scene-lead">${scene.lead}</p></div><div class="reveal-grid">${scene.cards.map((c,n)=>`<button class="reveal-card" data-reveal="${n}"><h3>${c[0]}</h3><p class="prompt">${c[1]}</p><p class="answer">${c[2]}</p></button>`).join('')}</div></div></div></section>`;
 if(scene.type==='assessmentIntro')return `<section class="scene" data-index="${i}"><div class="scene-inner"><div class="assessment-stage"><div class="assessment-card">${common}<h1 class="scene-title">${scene.title}</h1><p class="scene-lead">${scene.lead}</p><div class="assessment-meta"><span class="meta-pill">1 question</span><span class="meta-pill">~1 minute</span><span class="meta-pill">Practice score</span></div><button class="primary-action" data-jump="${i+1}">${state.lang==='en'?'Start Assessment':state.lang==='ja'?'評価を開始':state.lang==='zh-TW'?'開始評量':'开始考核'} ${icon('arrow')}</button></div></div></div></section>`;
 if(scene.type==='question')return `<section class="scene" data-index="${i}"><div class="scene-inner"><div class="question-stage"><div>${common}<h1 class="scene-title">${scene.title}</h1><p class="question-text">${scene.lead}</p><div class="feedback" id="feedback">${ui[state.lang].answerFirst}</div></div><div class="answer-list">${scene.options.map((o,n)=>`<button class="answer-option" data-answer="${n}"><span class="letter">${String.fromCharCode(65+n)}</span><span>${o}</span></button>`).join('')}</div></div></div></section>`;
 return `<section class="scene" data-index="${i}"><div class="scene-inner"><div class="completion-stage"><div class="completion-card">${common}<div style="width:92px;height:92px;border-radius:28px;display:grid;place-items:center;margin:0 auto 24px;background:rgba(67,214,160,.14);border:1px solid rgba(67,214,160,.5);color:var(--success)">${icon('check')}</div><h1 class="scene-title">${scene.title}</h1><p class="scene-lead">${scene.lead}</p><div class="assessment-meta"><span class="meta-pill">Micas brand lockup</span><span class="meta-pill">Fixed footer contract</span><span class="meta-pill">Responsive QA</span></div><button class="secondary-action" data-jump="0">${state.lang==='en'?'Replay Demo':state.lang==='ja'?'デモを再生':state.lang==='zh-TW'?'重新播放示範':'重新播放演示'}</button></div></div></div></section>`
}
