window.MICAS_CONTENT.en={title:'Micas Standard Interactive Training',scenes:[
  {module:'Welcome',title:'Train for the moment that matters',subtitle:'UI System Preview • Welcome',type:'hero',eyebrow:'Micas learning experience',lead:'A dark, presentation-first course shell built for clear decisions, complete technical visuals and confident delivery.',chips:['One-screen scenes','Four-language delivery','Offline-ready controls'],narration:'Welcome to the latest Micas interactive training user interface preview. This demo shows the approved header, full-screen stage, fixed footer, navigation, search, narration, language controls, and assessment transition.'},
  {module:'Design System',title:'One focal point per scene',subtitle:'UI System Preview • Visual hierarchy',type:'device',lead:'The content stage gives the dominant visual enough room to teach, while supporting points stay concise and readable.',points:[['Full view','Technical visuals remain complete and use contain behavior.'],['Clear hierarchy','A strong title, one dominant image, and three support points.'],['Dark stage','Light surfaces stay bounded inside technical frames.']],narration:'Each scene has one dominant learning message. Technical images remain fully visible, the stage stays deep navy, and supporting content remains concise.'},
  {module:'Design System',title:'Numbers lead. The logo breathes.',subtitle:'UI System Preview • Brand v3.1.10',type:'metrics',lead:'Adaptive sequence numbers use available card space, while the logo gains clear top, left and bottom breathing room without moving the title or controls.',metrics:[['34–52px','Standard sequence numbers'],['40–58px','Spacious sequence numbers'],['5–8px','Logo bottom clearance'],['4 languages','Custom dropdown']],narration:'Brand version three point one point ten raises standard sequence numbers to at least thirty-four pixels and allows spacious cards to use markers up to fifty-eight pixels. The company logo also keeps separate top, left, and bottom breathing room. This demo adds a consistent custom language dropdown without moving the title, utilities, or fixed rails.'},
  {module:'Learning Flow',title:'A clear learning path',subtitle:'UI System Preview • Scene architecture',type:'process',lead:'The course is reorganized around learning goals instead of mechanically copying source-page order.',steps:[['01','Orient','Establish why the topic matters.'],['02','Recognize','Identify concepts, states and visual cues.'],['03','Perform','Practice the operational sequence.'],['04','Verify','Review, assess and complete.']],narration:'The course follows a coherent learning path. It begins with orientation, moves through recognition and performance, then ends with review and assessment.'},
  {module:'Learning Flow',title:'Practice before assessment',subtitle:'UI System Preview • Interaction',type:'practice',lead:'Ungraded reveal interactions support exploration without interrupting global navigation.',cards:[['Reveal a principle','Click to reveal','Next stays available on every nonterminal scene.'],['Reveal a control rule','Click to reveal','Search is icon-only and appears immediately after Next.'],['Reveal a voice rule','Click to reveal','A matching Google voice is preferred whenever the browser exposes one.'],['Reveal a layout rule','Click to reveal','Overflow is solved by redesign or scene splitting—not tiny text.']],narration:'Instructional modules can include ungraded practice such as reveal cards and guided decisions. These interactions do not block global navigation.'},
  {module:'Review & Assessment',title:'Instruction complete',subtitle:'UI System Preview • Assessment transition',type:'assessmentIntro',lead:'The graded section begins only after a dedicated transition scene. Auto Play pauses here and waits for the learner.',narration:'Instruction is complete. The assessment introduction clearly explains the question count, approximate duration, scoring method, and how to proceed. Auto Play pauses here.'},
  {module:'Review & Assessment',title:'Check the approved footer order',subtitle:'UI System Preview • Question 1 of 1',type:'question',lead:'Which sequence matches the standard desktop right-side action cluster?',options:['Previous → Search → Next → narration → Audio settings','Previous → Next → Search → narration → Audio settings','Search → Previous → Next → Audio settings → narration','Previous → Next → narration → Search → Audio settings'],correct:1,narration:''},
  {module:'Complete',title:'Demo complete',subtitle:'UI System Preview • Completion',type:'complete',lead:'The latest shell keeps the Micas identity strong while making the course easier to present, navigate and use.',narration:'You have completed the Micas interactive training user interface demo.'}
 ]};
